ti-pru-cgt-installer
TexasInstruments/debian-repos pull request #13
Opened 2023-12-11 17:55 UTC by leonheldattoradex

The guys from BeagleBone maintained something like this for a long time. Instead of downloading the source everytime this is needed as a dependency, let's just have a package instead.

2023-12-12 23:24 UTC, glneo requested changes
Making a new ti-pru-cgt package is fine, but would be better to have the extracted tools in a repo and fetch that using the normal `export git_repo=` in verions.sh mechanism.

2023-12-12 23:24 UTC, glneo commented on ti-pru-cgt-installer/suite/bookworm/ti_cgt_pru_2.3.3_armlinuxa8hf_busybox_installer.sh
Why do you wan this huge binary file in the git repo? Why not use wget like we do currently.

2023-12-12 23:24 UTC, glneo commented on ti-pru-cgt-installer/version.sh
> +    (cd "${builddir}/${package_name}_${deb_version}" && debuild --no-lintian -i -us -uc -b)
We run debuild in the main script. I'm trying to remove this "run_custom_build", you shouldn't use it if not 100% needed.

2024-01-09 07:56 UTC, closed without merging

2024-01-09 08:00 UTC, sskartheekadivi commented
Ah!! Github closed this because you created the PR to my updates branch. @leonheldattoradex 
, Please create PRs on master if any.

2024-01-09 13:29 UTC, leonheldattoradex commented
@sskartheekadivi oh, thanks for the heads-up!
I'll get back on this as soon as possible.